// LOCALHOST 
### Get all
GET http://localhost:8080/groups 

### Get by ID
GET http://localhost:8080/groups/63362e49279ced902f21d832

### Create group 
POST http://localhost:8080/groups HTTP/1.1 
content-type: application/json

{
"name": "Group z",
"team1": "test",
"team2": "test",
"team3": "test",
"team4": "test"
}

### Update group 
PUT http://localhost:8080/groups/63362e9664e7757949cb398e HTTP/1.1 
content-type: application/json

{
"name": "Group zzz",
"team1": "test",
"team2": "test",
"team3": "test",
"team4": "test222"
} 
### DELETE group 
DELETE http://localhost:8080/groups/63362e9664e7757949cb398e HTTP/1.1



// PRODUCTION DEPLOY/// 
### Get all
GET https://cse341personal2.onrender.com/groups 

### Get by id
GET https://cse341personal2.onrender.com/groups/6326370ec8992a22706e79e2 

### Create group 
POST https://cse341personal2.onrender.com/groups HTTP/1.1 
content-type: application/json

{
"name": "Group z",
"team1": "test",
"team2": "test",
"team3": "test",
"team4": "test"
}

### Update group 
PUT https://cse341personal2.onrender.com/groups/632badeb167a80040175690a HTTP/1.1 
content-type: application/json

{
"name": "Group zzzz",
"team1": "test",
"team2": "test",
"team3": "test",
"team4": "test2222"
}

### DELETE group 
DELETE https://cse341personal2.onrender.com/groups/632badeb167a80040175690a HTTP/1.1
