// LOCALHOST 
### Get all
GET http://localhost:8080/groups 

### Get by ID
GET http://localhost:8080/groups/63362e49279ced902f21d832

### Create group 
POST http://localhost:8080/groups HTTP/1.1 
content-type: application/json

{
"name": "Group z",
"team1": "test",
"team2": "test",
"team3": "test",
"team4": "test"
}

### Update group
PUT http://localhost:8080/groups/63362e9664e7757949cb398e HTTP/1.1 
content-type: application/json

{
"name": "Group zzz",
"team1": "test",
"team2": "test",
"team3": "test",
"team4": "test222"
} 
### DELETE group 
DELETE http://localhost:8080/groups/63362e9664e7757949cb398e HTTP/1.1



// PRODUCTION DEPLOY/// 
### Get all 
GET https://carlosworldcup2022.onrender.com/groups 

### Get by id
GET https://carlosworldcup2022.onrender.com/groups/63362e49279ced902f21d832

### Create group 
POST https://carlosworldcup2022.onrender.com/groups HTTP/1.1 
content-type: application/json

{
"name": "Group z",
"team1": "test",
"team2": "test",
"team3": "test",
"team4": "test"
}

### Update group 
PUT https://carlosworldcup2022.onrender.com/groups/633635788124bf34ee53ebb2 HTTP/1.1 
content-type: application/json

{
"name": "Group zzzz",
"team1": "test",
"team2": "test",
"team3": "test",
"team4": "test2222"
}

### DELETE group 
DELETE https://carlosworldcup2022.onrender.com/groups/633635788124bf34ee53ebb2 HTTP/1.1
